@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "64e7b84e45336a6b8f7852d4",
  "receiverId": "64e3c597ea8e49bb7358d355",
  "receiverUsername": "Ganny",
  "receiverAvatarColor": "red",
  "receiverProfilePicture": "https://res.cloudinary.com/da1xnru4v/image/upload/v1692648855/64e3c597ea8e49bb7358d355",
  "body": "No man",
  "gifUrl": "",
  "isRead": true,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "64e3c2fdea8e49bb7358d33b",
  "userTwo": "64e3c597ea8e49bb7358d355"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "62f2962c6b761b208a728e91",
  "userTwo": "62f29f71da585226216b2724"
}

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/64e3c597ea8e49bb7358d355
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/64e871d87f3ee55f3b9fe8f0/64e3c2fdea8e49bb7358d33b/64e3c597ea8e49bb7358d355/deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "64e3c2fdea8e49bb7358d33b",
  "receiverId": "64e3c597ea8e49bb7358d355"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "64e7b84e45336a6b8f7852d4",
  "messageId": "64e8f6e0f27cfcf661d3e930",
  "reaction": "sad",
  "type": "remove"
}
