@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64c39e675f5517f7faebb525",  //mohsin
  "postId": "64db5f49e52e07570c1ddd70",  //mohsin
  "type": "like",
  "previousReaction": "",
  "postReactions": 	{"like":1,"love":0,"happy":0,"sad":0,"wow":0,"angry":0},
  "profilePicture": "https://res.cloudinary.com/da1xnru4v/image/upload/v1690541673/64c39e675f5517f7faebb525"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/64db5f49e52e07570c1ddd70/wow/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/64db5f49e52e07570c1ddd70
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Danny/64db5f49e52e07570c1ddd70
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Danny
Content-Type: application/json
Accept: application/json
withCredentials: true
