@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/user/all/1
# GET {{baseUrl}}/{{urlPath}}/user/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/64e3c308ea8e49bb7358d342
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/posts/danny/64e3c2fdea8e49bb7358d33b/155374601869
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/user/suggestions
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/search/g
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/change-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "currentPassword": "querty",
  "newPassword": "querty1",
  "confirmPassword": "querty1"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/basic-info
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "quote": "Do it now",
  "work": "",
  "school": "Amity",
  "location": "Noida"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/social-links
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "instagram": "",
  "twitter": "",
  "facebook": "https://www.facebook.com/",
  "youtube": "https://www.youtube.com/"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/settings
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "messages": false,
  "reactions": true,
  "comments": false,
  "follows": true
}
